# Generated by Django 4.1.3 on 2023-07-03 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('school', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
                ('reviewed', models.BooleanField(default=False)),
            ],
        ),
    ]
