# Generated by Django 4.1.3 on 2023-07-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_form', '0002_registrationform_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationform',
            name='how_found',
            field=models.CharField(default='Other', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrationform',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
    ]
